In [1]:
import numpy as npa
import pandas as pd
from pandas import read_csv
import pickle
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder
from timeseires.utils import t_v_t_split as sp

In [2]:
df=pd.read_csv(r'C:\Users\Muhammad Luqman\Desktop\OPEN_ENDED_LAB_21JZELE0444_LUQMAN\5_features_extracted.csv', index_col=['Datetime'], parse_dates=['Datetime'])
df.head()

,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
Datetime,,,,,,,,,,,
2024-01-01 00:00:00,0.22,1,0,0,1,0,0,0,0,1,0
2024-01-01 01:00:00,0.22,1,0,0,1,0,0,0,1,1,0
2024-01-01 02:00:00,0.22,1,0,0,1,0,0,0,2,1,0
2024-01-01 03:00:00,0.22,1,0,0,1,0,0,0,3,1,0
2024-01-01 04:00:00,0.22,1,0,0,1,0,0,0,4,1,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8760 entries, 2024-01-01 00:00:00 to 2024-12-30 23:00:00
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   aep          8760 non-null   float64
 1   year_day     8760 non-null   int64
 2   holiday      8760 non-null   int64
 3   weekend      8760 non-null   int64
 4   winter       8760 non-null   int64
 5   spring       8760 non-null   int64
 6   summer       8760 non-null   int64
 7   fall         8760 non-null   int64
 8   hour         8760 non-null   int64
 9   month        8760 non-null   int64
 10  day_of_week  8760 non-null   int64
dtypes: float64(1), int64(10)
memory usage: 821.2 KB

# Function to split data For Training, Validation & Test

# tarin, test &  validation split

In [4]:
train_set , validation_set , test_set = sp.t_v_t(df,70,20,10)

In [5]:
print(train_set.shape)
print(validation_set.shape)
print(test_set.shape)

(6132, 11)
(1752, 11)
(876, 11)

In [6]:
(84907+24259+12130)-121296

0

In [7]:
test_set

,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
Datetime,,,,,,,,,,,
2024-11-24 12:00:00,0.22,329,0,1,0,0,0,1,12,11,6
2024-11-24 13:00:00,0.22,329,0,1,0,0,0,1,13,11,6
2024-11-24 14:00:00,0.22,329,0,1,0,0,0,1,14,11,6
2024-11-24 15:00:00,0.22,329,0,1,0,0,0,1,15,11,6
2024-11-24 16:00:00,0.22,329,0,1,0,0,0,1,16,11,6
...,...,...,...,...,...,...,...,...,...,...,...
2024-12-30 19:00:00,0.22,365,0,0,1,0,0,0,19,12,0
2024-12-30 20:00:00,0.22,365,0,0,1,0,0,0,20,12,0
2024-12-30 21:00:00,0.22,365,0,0,1,0,0,0,21,12,0
2024-12-30 22:00:00,0.22,365,0,0,1,0,0,0,22,12,0
2024-12-30 23:00:00,0.22,365,0,0,1,0,0,0,23,12,0

# Train

##### MinMax

In [8]:
train_set_load             = train_set['aep'].values.reshape(-1, 1)              
validation_set_load        = validation_set['aep'].values.reshape(-1, 1)
test_set_load              = test_set['aep'].values.reshape(-1, 1)
#.........................................................................
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(train_set_load)
#scaler = StandardScaler()
#scaler.fit(train_set_load)
#.........................................................................
scaled_train_set_load      = scaler.transform(train_set_load)
scaled_validation_set_load = scaler.transform(validation_set_load)
scaled_test_set_load       = scaler.transform(test_set_load)
pickle.dump(scaler, open ("AEPscaler.pkl",'wb') )
scaled_train_set_load.shape

(6132, 1)

In [9]:
train_numerical = scaled_train_set_load
train_numerical.shape

(6132, 1)

In [10]:
train_set.describe()

,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
count,6132.000000,6132.000000,6132.0,6132.000000,6132.000000,6132.000000,6132.000000,6132.000000,6132.000000,6132.000000,6132.000000
mean,0.212387,128.250489,0.0,0.281800,0.234834,0.360078,0.360078,0.045010,11.488258,4.718200,2.976517
std,0.004264,73.762794,0.0,0.449913,0.423929,0.480062,0.480062,0.207343,6.922741,2.429399,2.000025
min,0.210000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,0.210000,64.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,3.000000,1.000000
50%,0.210000,128.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,5.000000,3.000000
75%,0.210000,192.000000,0.0,1.000000,0.000000,1.000000,1.000000,0.000000,17.000000,7.000000,5.000000
max,0.220000,256.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,23.000000,9.000000,6.000000

In [11]:
(12379.-9669.)/(22556.0-9669)

0.21028943896950414

In [12]:
train_numerical

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

##### OneHot Encoding

In [13]:
df.columns

Index(['aep', 'year_day', 'holiday', 'weekend', 'winter', 'spring', 'summer',
       'fall', 'hour', 'month', 'day_of_week'],
      dtype='object')

In [14]:
_=df.columns
_[2],_[3]

('holiday', 'weekend')

In [15]:
train_set

,aep,year_day,holiday,weekend,winter,spring,summer,fall,hour,month,day_of_week
Datetime,,,,,,,,,,,
2024-01-01 00:00:00,0.22,1,0,0,1,0,0,0,0,1,0
2024-01-01 01:00:00,0.22,1,0,0,1,0,0,0,1,1,0
2024-01-01 02:00:00,0.22,1,0,0,1,0,0,0,2,1,0
2024-01-01 03:00:00,0.22,1,0,0,1,0,0,0,3,1,0
2024-01-01 04:00:00,0.22,1,0,0,1,0,0,0,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...
2024-09-12 07:00:00,0.21,256,0,0,0,0,0,1,7,9,3
2024-09-12 08:00:00,0.21,256,0,0,0,0,0,1,8,9,3
2024-09-12 09:00:00,0.21,256,0,0,0,0,0,1,9,9,3
2024-09-12 10:00:00,0.21,256,0,0,0,0,0,1,10,9,3
2024-09-12 11:00:00,0.21,256,0,0,0,0,0,1,11,9,3

In [16]:
import numpy as np
train_setO     = train_set[:].values

holiday        = train_setO[:,2:3]
weekend        = train_setO[:,3:4]


en_holiday     = OneHotEncoder(handle_unknown='ignore')
en_weekend    = OneHotEncoder(handle_unknown='ignore')


holidayf       = en_holiday.fit(holiday)             #2
holidayt       = holidayf.transform(holiday).toarray() 

weekendf       = en_weekend.fit(weekend)             #2
weekendt       = weekendf.transform(weekend).toarray()




train_categorical = np.concatenate((holidayt,weekendt), axis=1)
train_categorical.shape

(6132, 3)

##### Cyclic

In [17]:
df.columns

Index(['aep', 'year_day', 'holiday', 'weekend', 'winter', 'spring', 'summer',
       'fall', 'hour', 'month', 'day_of_week'],
      dtype='object')

In [18]:
cyclic_train = train_set[['month','day_of_week','hour','winter', 'spring', 'summer','fall','year_day']]
cyclic_train = cyclic_train[:].values


sin_montht   = np.sin(2*np.pi*cyclic_train[:,0:1]/12)
cos_montht   = np.cos(2*np.pi*cyclic_train[:,0:1]/12)

sin_weekt    = np.sin(2*np.pi*cyclic_train[:,1:2]/6)
cos_weekt    = np.cos(2*np.pi*cyclic_train[:,1:2]/6)
  
sin_hourt    = np.sin(2*np.pi*cyclic_train[:,2:3]/24)
cos_hourt    = np.cos(2*np.pi*cyclic_train[:,2:3]/24)

sin_wintert    = np.sin(2*np.pi*cyclic_train[:,3:4]/4)
cos_wintert    = np.cos(2*np.pi*cyclic_train[:,3:4]/4)

sin_springt    = np.sin(2*np.pi*cyclic_train[:,4:5]/4)
cos_springt    = np.cos(2*np.pi*cyclic_train[:,4:5]/4)

sin_summert    = np.sin(2*np.pi*cyclic_train[:,5:6]/4)
cos_summert    = np.cos(2*np.pi*cyclic_train[:,5:6]/4)

sin_fallt    = np.sin(2*np.pi*cyclic_train[:,6:7]/4)
cos_fallt    = np.cos(2*np.pi*cyclic_train[:,6:7]/4)

sin_year_dayt    = np.sin(2*np.pi*cyclic_train[:,7:8]/365)
cos_year_dayt    = np.cos(2*np.pi*cyclic_train[:,7:8]/365)

train_cyclic = np.concatenate((sin_montht, cos_montht, 
                               sin_weekt, cos_weekt, 
                               sin_hourt,cos_hourt,
                               sin_wintert,cos_wintert,
                               sin_springt,cos_springt,
                               sin_summert ,cos_summert,
                               sin_fallt,cos_fallt,
                              sin_year_dayt ,cos_year_dayt ), axis=1)

In [19]:
train = np.concatenate((train_numerical,train_categorical, train_cyclic), axis=1)
train.shape

(6132, 20)

In [21]:
train_df = pd.DataFrame(
    data=train.transpose(),
    index=[
        'aep',
        'Is_holiday1', 'Is_holiday2',
        'Is_Weekend1', 'Is_Weekend2',
        'sin_month', 'cos_month',
        'sin_week', 'cos_week',
        'sin_hour', 'cos_hour',
        'sin_wintert', 'cos_wintert',
        'sin_springt', 'cos_springt',
        'sin_summert', 'cos_summert',
        'sin_fallt', 'cos_fallt',
        'sin_year_dayt'  # ← Removed extra space and 21st label
    ]
).transpose()

In [22]:
train_df.to_csv('7_AEP_train.csv', index=False)

# validation

##### MinMax

In [23]:
validation_numerical = scaled_validation_set_load
validation_numerical.shape

(1752, 1)

#### OneHot

In [24]:

validation_setO = validation_set[:].values

holiday        = validation_setO[:,2:3]
weekend        = validation_setO[:,3:4]



holidayt       = holidayf.transform(holiday).toarray() 

weekendt       = weekendf.transform(weekend).toarray()
            
                                                        
            
validation_categorical = np.concatenate((holidayt,weekendt), axis=1)
validation_categorical.shape

(1752, 3)

#### cyclic

In [25]:
cyclic_validation = validation_set[['month','day_of_week','hour','winter', 'spring', 'summer','fall','year_day']]
cyclic_validation = cyclic_validation[:].values

sin_montht   = np.sin(2*np.pi*cyclic_validation[:,0:1]/12)
cos_montht   = np.cos(2*np.pi*cyclic_validation[:,0:1]/12)

sin_weekt    = np.sin(2*np.pi*cyclic_validation[:,1:2]/6)
cos_weekt    = np.cos(2*np.pi*cyclic_validation[:,1:2]/6)
  
sin_hourt    = np.sin(2*np.pi*cyclic_validation[:,2:3]/24)
cos_hourt    = np.cos(2*np.pi*cyclic_validation[:,2:3]/24)

sin_wintert    = np.sin(2*np.pi*cyclic_validation[:,3:4]/4)
cos_wintert    = np.cos(2*np.pi*cyclic_validation[:,3:4]/4)

sin_springt    = np.sin(2*np.pi*cyclic_validation[:,4:5]/4)
cos_springt    = np.cos(2*np.pi*cyclic_validation[:,4:5]/4)

sin_summert    = np.sin(2*np.pi*cyclic_validation[:,5:6]/4)
cos_summert    = np.cos(2*np.pi*cyclic_validation[:,5:6]/4)

sin_fallt    = np.sin(2*np.pi*cyclic_validation[:,6:7]/4)
cos_fallt    = np.cos(2*np.pi*cyclic_validation[:,6:7]/4)

sin_year_dayt    = np.sin(2*np.pi*cyclic_validation[:,7:8]/365)
cos_year_dayt    = np.cos(2*np.pi*cyclic_validation[:,7:8]/365)

validation_cyclic = np.concatenate((sin_montht, cos_montht, 
                               sin_weekt, cos_weekt, 
                               sin_hourt,cos_hourt,
                               sin_wintert,cos_wintert,
                               sin_springt,cos_springt,
                               sin_summert ,cos_summert,
                               sin_fallt,cos_fallt,sin_year_dayt,cos_year_dayt), axis=1) 

validation_cyclic.shape

(1752, 16)

In [26]:
validation = np.concatenate((validation_numerical,validation_categorical, validation_cyclic), axis=1)
validation.shape

(1752, 20)

In [29]:
validation_df = pd.DataFrame(
    data=validation.transpose(),
    index=[
        'aep',
        'Is_holiday1', 'Is_holiday2',
        'Is_Weekend1', 'Is_Weekend2',
        'sin_month', 'cos_month',
        'sin_week', 'cos_week',
        'sin_hour', 'cos_hour',
        'sin_wintert', 'cos_wintert',
        'sin_springt', 'cos_springt',
        'sin_summert', 'cos_summert',
        'sin_fallt', 'cos_fallt',
        # Remove one of these to make the list 20 total
        'sin_year_dayt'  # ← Keep only one of the year-day components if needed
        # 'cos_year_dayt'  ← Commented or removed
    ]
).transpose()

In [30]:
validation_df.to_csv('8_AEP_validation.csv', index=False)

In [31]:
validation_df.shape

(1752, 20)

# Test

##### MinMax

In [32]:
test_numerical = scaled_test_set_load
test_numerical.shape

(876, 1)

##### OneHot

In [33]:

test_setO = test_set[:].values

holiday        = test_setO[:,2:3]
weekend        = test_setO[:,3:4]



holidayt       = holidayf.transform(holiday).toarray() 

weekendt       = weekendf.transform(weekend).toarray()
            
                                                        
            
test_categorical = np.concatenate((holidayt,weekendt), axis=1)
test_categorical.shape

(876, 3)

##### cyclic

In [34]:
cyclic_test = test_set[['month','day_of_week','hour','winter', 'spring', 'summer','fall', 'year_day']]
cyclic_test = cyclic_test[:].values

sin_montht   = np.sin(2*np.pi*cyclic_test[:,0:1]/12)
cos_montht   = np.cos(2*np.pi*cyclic_test[:,0:1]/12)

sin_weekt    = np.sin(2*np.pi*cyclic_test[:,1:2]/6)
cos_weekt    = np.cos(2*np.pi*cyclic_test[:,1:2]/6)
  
sin_hourt    = np.sin(2*np.pi*cyclic_test[:,2:3]/24)
cos_hourt    = np.cos(2*np.pi*cyclic_test[:,2:3]/24)

sin_wintert    = np.sin(2*np.pi*cyclic_test[:,3:4]/4)
cos_wintert    = np.cos(2*np.pi*cyclic_test[:,3:4]/4)

sin_springt    = np.sin(2*np.pi*cyclic_test[:,4:5]/4)
cos_springt    = np.cos(2*np.pi*cyclic_test[:,4:5]/4)

sin_summert    = np.sin(2*np.pi*cyclic_test[:,5:6]/4)
cos_summert    = np.cos(2*np.pi*cyclic_test[:,5:6]/4)

sin_fallt    = np.sin(2*np.pi*cyclic_test[:,6:7]/4)
cos_fallt    = np.cos(2*np.pi*cyclic_test[:,6:7]/4)

sin_year_dayt    = np.sin(2*np.pi*cyclic_test[:,7:8]/365)
cos_year_dayt    = np.cos(2*np.pi*cyclic_test[:,7:8]/365)

test_cyclic = np.concatenate((sin_montht, cos_montht, 
                               sin_weekt, cos_weekt, 
                               sin_hourt,cos_hourt,
                               sin_wintert,cos_wintert,
                               sin_springt,cos_springt,
                               sin_summert ,cos_summert,
                               sin_fallt,cos_fallt,sin_year_dayt,cos_year_dayt ), axis=1) 

test_cyclic.shape

(876, 16)

In [35]:
test = np.concatenate((test_numerical,test_categorical, test_cyclic), axis=1)
test.shape

(876, 20)

In [37]:
test_df = pd.DataFrame(
    data=test.transpose(),
    index=[
        'aep',
        'Is_holiday1', 'Is_holiday2',
        'Is_Weekend1', 'Is_Weekend2',
        'sin_month', 'cos_month',
        'sin_week', 'cos_week',
        'sin_hour', 'cos_hour',
        'sin_wintert', 'cos_wintert',
        'sin_springt', 'cos_springt',
        'sin_summert', 'cos_summert',
        'sin_fallt', 'cos_fallt',
        'sin_year_dayt'  # ❌ remove 'cos_year_dayt' if only 20 features are in `test`
    ]
).transpose()

In [38]:
test_df.to_csv('9_AEP_test.csv', index=False)

In [39]:
test_df.shape

(876, 20)

In [40]:
4*((24*24)+24^2+24)

2312

In [41]:
(84907)/(10*(24+24))

176.88958333333332

In [42]:
84907

84907