In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\Muhammad Luqman\Desktop\OPEN_ENDED_LAB_21JZELE0444_LUQMAN\3_Outlier_Identified.csv',parse_dates=['Datetime'])
df.head()

             Datetime  AEP_MW
0 2024-01-01 00:00:00    0.22
1 2024-01-01 01:00:00    0.22
2 2024-01-01 02:00:00    0.22
3 2024-01-01 03:00:00    0.22
4 2024-01-01 04:00:00    0.22

In [3]:
df['Date'] = df['Datetime'].dt.normalize()

In [6]:
df.iloc[0:50]

              Datetime  AEP_MW       Date
0  2024-01-01 00:00:00    0.22 2024-01-01
1  2024-01-01 01:00:00    0.22 2024-01-01
2  2024-01-01 02:00:00    0.22 2024-01-01
3  2024-01-01 03:00:00    0.22 2024-01-01
4  2024-01-01 04:00:00    0.22 2024-01-01
5  2024-01-01 05:00:00    0.22 2024-01-01
6  2024-01-01 06:00:00    0.22 2024-01-01
7  2024-01-01 07:00:00    0.22 2024-01-01
8  2024-01-01 08:00:00    0.22 2024-01-01
9  2024-01-01 09:00:00    0.22 2024-01-01
10 2024-01-01 10:00:00    0.22 2024-01-01
11 2024-01-01 11:00:00    0.22 2024-01-01
12 2024-01-01 12:00:00    0.22 2024-01-01
13 2024-01-01 13:00:00    0.22 2024-01-01
14 2024-01-01 14:00:00    0.22 2024-01-01
15 2024-01-01 15:00:00    0.22 2024-01-01
16 2024-01-01 16:00:00    0.22 2024-01-01
17 2024-01-01 17:00:00    0.22 2024-01-01
18 2024-01-01 18:00:00    0.22 2024-01-01
19 2024-01-01 19:00:00    0.22 2024-01-01
20 2024-01-01 20:00:00    0.22 2024-01-01
21 2024-01-01 21:00:00    0.22 2024-01-01
22 2024-01-01 22:00:00    0.22 2024-01-01
23 2024-01-01 23:00:00    0.22 2024-01-01
24 2024-01-02 00:00:00    0.22 2024-01-02
25 2024-01-02 01:00:00    0.22 2024-01-02
26 2024-01-02 02:00:00    0.22 2024-01-02
27 2024-01-02 03:00:00    0.22 2024-01-02
28 2024-01-02 04:00:00    0.22 2024-01-02
29 2024-01-02 05:00:00    0.22 2024-01-02
30 2024-01-02 06:00:00    0.22 2024-01-02
31 2024-01-02 07:00:00    0.22 2024-01-02
32 2024-01-02 08:00:00    0.22 2024-01-02
33 2024-01-02 09:00:00    0.22 2024-01-02
34 2024-01-02 10:00:00    0.22 2024-01-02
35 2024-01-02 11:00:00    0.22 2024-01-02
36 2024-01-02 12:00:00    0.22 2024-01-02
37 2024-01-02 13:00:00    0.22 2024-01-02
38 2024-01-02 14:00:00    0.22 2024-01-02
39 2024-01-02 15:00:00    0.22 2024-01-02
40 2024-01-02 16:00:00    0.22 2024-01-02
41 2024-01-02 17:00:00    0.22 2024-01-02
42 2024-01-02 18:00:00    0.22 2024-01-02
43 2024-01-02 19:00:00    0.22 2024-01-02
44 2024-01-02 20:00:00    0.22 2024-01-02
45 2024-01-02 21:00:00    0.22 2024-01-02
46 2024-01-02 22:00:00    0.22 2024-01-02
47 2024-01-02 23:00:00    0.22 2024-01-02
48 2024-01-03 00:00:00    0.22 2024-01-03
49 2024-01-03 01:00:00    0.22 2024-01-03

In [7]:
len(df)

8760

In [8]:
holiday=pd.read_csv(r'C:\Users\Muhammad Luqman\Desktop\OPEN_ENDED_LAB_21JZELE0444_LUQMAN\processed_holiday.csv',parse_dates=['Date'])

In [9]:
holiday.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     279 non-null    datetime64[ns]
 1   Holiday  279 non-null    object
 2   WeekDay  279 non-null    object
 3   Month    279 non-null    int64
 4   Day      279 non-null    int64
 5   Year     279 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 13.2+ KB

In [10]:
holiday.head()

        Date                      Holiday   WeekDay  Month  Day  Year
0 2004-01-01               New Year's Day  Thursday      1    1  2004
1 2004-01-19  Martin Luther King, Jr. Day    Monday      1   19  2004
2 2004-02-14              Valentine’s Day  Saturday      2   14  2004
3 2004-02-16        Washington's Birthday    Monday      2   16  2004
4 2004-04-11               Eastern Easter    Sunday      4   11  2004

In [11]:
holiday.drop(['WeekDay','Month','Day','Year'],axis=1, inplace=True)

In [12]:
(len(holiday)*24)-(21*24) #in 2004 first 9 month is not include which includes 11 holidays.
                           #similarly in 2018 last 5 month not included which incluede 10 holidays.  21 total

6192

In [13]:
mergedf = pd.merge(df, holiday, on= 'Date', how="left")
mergedf

                Datetime  AEP_MW       Date Holiday
0    2024-01-01 00:00:00    0.22 2024-01-01     NaN
1    2024-01-01 01:00:00    0.22 2024-01-01     NaN
2    2024-01-01 02:00:00    0.22 2024-01-01     NaN
3    2024-01-01 03:00:00    0.22 2024-01-01     NaN
4    2024-01-01 04:00:00    0.22 2024-01-01     NaN
...                  ...     ...        ...     ...
8755 2024-12-30 19:00:00    0.22 2024-12-30     NaN
8756 2024-12-30 20:00:00    0.22 2024-12-30     NaN
8757 2024-12-30 21:00:00    0.22 2024-12-30     NaN
8758 2024-12-30 22:00:00    0.22 2024-12-30     NaN
8759 2024-12-30 23:00:00    0.22 2024-12-30     NaN

[8760 rows x 4 columns]

In [14]:
#
mergedf['Holiday'].isna().sum()

8760

In [15]:
#121416
121296-mergedf['Holiday'].isna().sum()

112536

In [16]:
mergedf['Holiday'] = mergedf['Holiday'].notnull().astype("int")

In [17]:
mergedf.head()

             Datetime  AEP_MW       Date  Holiday
0 2024-01-01 00:00:00    0.22 2024-01-01        0
1 2024-01-01 01:00:00    0.22 2024-01-01        0
2 2024-01-01 02:00:00    0.22 2024-01-01        0
3 2024-01-01 03:00:00    0.22 2024-01-01        0
4 2024-01-01 04:00:00    0.22 2024-01-01        0

In [18]:
mergedf.to_csv(r'C:\Users\Muhammad Luqman\Desktop\OPEN_ENDED_LAB_21JZELE0444_LUQMAN\4_AEP_Introducing_holidays.csv',index=False)

In [19]:
mergedf[2000:2060]

                Datetime  AEP_MW       Date  Holiday
2000 2024-03-24 08:00:00    0.21 2024-03-24        0
2001 2024-03-24 09:00:00    0.21 2024-03-24        0
2002 2024-03-24 10:00:00    0.21 2024-03-24        0
2003 2024-03-24 11:00:00    0.21 2024-03-24        0
2004 2024-03-24 12:00:00    0.21 2024-03-24        0
2005 2024-03-24 13:00:00    0.21 2024-03-24        0
2006 2024-03-24 14:00:00    0.21 2024-03-24        0
2007 2024-03-24 15:00:00    0.21 2024-03-24        0
2008 2024-03-24 16:00:00    0.21 2024-03-24        0
2009 2024-03-24 17:00:00    0.21 2024-03-24        0
2010 2024-03-24 18:00:00    0.21 2024-03-24        0
2011 2024-03-24 19:00:00    0.21 2024-03-24        0
2012 2024-03-24 20:00:00    0.21 2024-03-24        0
2013 2024-03-24 21:00:00    0.21 2024-03-24        0
2014 2024-03-24 22:00:00    0.21 2024-03-24        0
2015 2024-03-24 23:00:00    0.21 2024-03-24        0
2016 2024-03-25 00:00:00    0.21 2024-03-25        0
2017 2024-03-25 01:00:00    0.21 2024-03-25        0
2018 2024-03-25 02:00:00    0.21 2024-03-25        0
2019 2024-03-25 03:00:00    0.21 2024-03-25        0
2020 2024-03-25 04:00:00    0.21 2024-03-25        0
2021 2024-03-25 05:00:00    0.21 2024-03-25        0
2022 2024-03-25 06:00:00    0.21 2024-03-25        0
2023 2024-03-25 07:00:00    0.21 2024-03-25        0
2024 2024-03-25 08:00:00    0.21 2024-03-25        0
2025 2024-03-25 09:00:00    0.21 2024-03-25        0
2026 2024-03-25 10:00:00    0.21 2024-03-25        0
2027 2024-03-25 11:00:00    0.21 2024-03-25        0
2028 2024-03-25 12:00:00    0.21 2024-03-25        0
2029 2024-03-25 13:00:00    0.21 2024-03-25        0
2030 2024-03-25 14:00:00    0.21 2024-03-25        0
2031 2024-03-25 15:00:00    0.21 2024-03-25        0
2032 2024-03-25 16:00:00    0.21 2024-03-25        0
2033 2024-03-25 17:00:00    0.21 2024-03-25        0
2034 2024-03-25 18:00:00    0.21 2024-03-25        0
2035 2024-03-25 19:00:00    0.21 2024-03-25        0
2036 2024-03-25 20:00:00    0.21 2024-03-25        0
2037 2024-03-25 21:00:00    0.21 2024-03-25        0
2038 2024-03-25 22:00:00    0.21 2024-03-25        0
2039 2024-03-25 23:00:00    0.21 2024-03-25        0
2040 2024-03-26 00:00:00    0.21 2024-03-26        0
2041 2024-03-26 01:00:00    0.21 2024-03-26        0
2042 2024-03-26 02:00:00    0.21 2024-03-26        0
2043 2024-03-26 03:00:00    0.21 2024-03-26        0
2044 2024-03-26 04:00:00    0.21 2024-03-26        0
2045 2024-03-26 05:00:00    0.21 2024-03-26        0
2046 2024-03-26 06:00:00    0.21 2024-03-26        0
2047 2024-03-26 07:00:00    0.21 2024-03-26        0
2048 2024-03-26 08:00:00    0.21 2024-03-26        0
2049 2024-03-26 09:00:00    0.21 2024-03-26        0
2050 2024-03-26 10:00:00    0.21 2024-03-26        0
2051 2024-03-26 11:00:00    0.21 2024-03-26        0
2052 2024-03-26 12:00:00    0.21 2024-03-26        0
2053 2024-03-26 13:00:00    0.21 2024-03-26        0
2054 2024-03-26 14:00:00    0.21 2024-03-26        0
2055 2024-03-26 15:00:00    0.21 2024-03-26        0
2056 2024-03-26 16:00:00    0.21 2024-03-26        0
2057 2024-03-26 17:00:00    0.21 2024-03-26        0
2058 2024-03-26 18:00:00    0.21 2024-03-26        0
2059 2024-03-26 19:00:00    0.21 2024-03-26        0

In [20]:
df.isnull().sum()

Datetime    0
AEP_MW      0
Date        0
dtype: int64