In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv(r'C:\Users\Muhammad Luqman\Desktop\OPEN_ENDED_LAB_21JZELE0444_LUQMAN\merged_two_column_data.csv' ,parse_dates=True)

In [3]:
df.head()

              Datetime  AEP_MW
0  2024-01-01 00:00:00    0.22
1  2024-01-01 01:00:00    0.22
2  2024-01-01 02:00:00    0.22
3  2024-01-01 03:00:00    0.22
4  2024-01-01 04:00:00    0.22

In [4]:
df.tail()

                  Datetime    AEP_MW
35035  2024-12-30 19:00:00  1.604967
35036  2024-12-30 20:00:00  0.803133
35037  2024-12-30 21:00:00  2.194633
35038  2024-12-30 22:00:00  1.456333
35039  2024-12-30 23:00:00  3.310950

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  35040 non-null  object
 1   AEP_MW    35040 non-null  float64
dtypes: float64(1), object(1)
memory usage: 547.6+ KB

In [6]:
df.describe()

             AEP_MW
count  3.504000e+04
mean   4.583720e+00
std    7.317579e+00
min    9.752910e-08
25%    2.100000e-01
50%    4.000000e-01
75%    5.661937e+00
max    3.220000e+01

### Dataset info
Oct 2004 to Aug 2018

In [7]:
# 2004
(24*31*2)+24*30

2208

In [8]:
# 2018
(24*31*4)+(24*30*2)+24*28+24*2+1

5137

info:
    Jan, march, May, July, Aug, oct, dec ---->31
    April, june, sept, Nov ----> 30
    Feb -----> 28/ 29

In [9]:
total = ((24*31*2)+24*30) +  (24*31*7)*13+(24*30*4)*13+(24*28*1)*10+(24*29*1)*3  +  (24*31*4)+(24*30*2)+24*28+24*2+1
total

121297

In [10]:
print('Missing= ',  121297 - len(df))

Missing=  86257

In [11]:
print('Data Points= ',  len(df))
print('Samples= ',      int(len(df)/24))

Data Points=  35040
Samples=  1460

In [12]:
# Drop Duplicates Except the First Occurrence
df.drop_duplicates(subset=['Datetime'], keep ='first',  inplace= True)
print('len = ',len(df))

len =  8760

In [13]:
df['Datetime']=pd.to_datetime(df['Datetime'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8760 entries, 0 to 8759
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  8760 non-null   datetime64[ns]
 1   AEP_MW    8760 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 205.3 KB

In [14]:
df

                Datetime  AEP_MW
0    2024-01-01 00:00:00    0.22
1    2024-01-01 01:00:00    0.22
2    2024-01-01 02:00:00    0.22
3    2024-01-01 03:00:00    0.22
4    2024-01-01 04:00:00    0.22
...                  ...     ...
8755 2024-12-30 19:00:00    0.54
8756 2024-12-30 20:00:00    0.54
8757 2024-12-30 21:00:00    0.22
8758 2024-12-30 22:00:00    0.22
8759 2024-12-30 23:00:00    0.22

[8760 rows x 2 columns]

In [15]:
df.set_index('Datetime', inplace=True)
df.head()

                     AEP_MW
Datetime
2024-01-01 00:00:00    0.22
2024-01-01 01:00:00    0.22
2024-01-01 02:00:00    0.22
2024-01-01 03:00:00    0.22
2024-01-01 04:00:00    0.22

In [16]:
df.iloc[22:25]

                     AEP_MW
Datetime
2024-01-01 22:00:00    0.22
2024-01-01 23:00:00    0.22
2024-01-02 00:00:00    0.22

In [17]:
df=df.sort_index(ascending=True)
df.iloc[22:25]

                     AEP_MW
Datetime
2024-01-01 22:00:00    0.22
2024-01-01 23:00:00    0.22
2024-01-02 00:00:00    0.22

In [18]:
print(df.head(1))
print(df.tail(1))

            AEP_MW
Datetime
2024-01-01    0.22
                     AEP_MW
Datetime
2024-12-30 23:00:00    0.22

In [19]:
missing_Timestamp=pd.date_range('2004-10-01','2018-08-03',freq='H').difference(df.index)
print('\nNumber of Missing Timestamp= ',len(missing_Timestamp),'\n')
print(missing_Timestamp.to_list())

Number of Missing Timestamp=  121297

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [20]:
df

                     AEP_MW
Datetime
2024-01-01 00:00:00    0.22
2024-01-01 01:00:00    0.22
2024-01-01 02:00:00    0.22
2024-01-01 03:00:00    0.22
2024-01-01 04:00:00    0.22
...                     ...
2024-12-30 19:00:00    0.54
2024-12-30 20:00:00    0.54
2024-12-30 21:00:00    0.22
2024-12-30 22:00:00    0.22
2024-12-30 23:00:00    0.22

[8760 rows x 1 columns]

In [21]:
df = df.resample('H').first().fillna(np.NaN)
missing_Timestamp=pd.date_range('2004-10-01','2018-08-03',freq='H').difference(df.index)
print('\nNumber of Missing Timestamp= ',len(missing_Timestamp),'\n')
print(missing_Timestamp.to_list())

Number of Missing Timestamp=  121297

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [22]:
df.tail(1)

                     AEP_MW
Datetime
2024-12-30 23:00:00    0.22

In [23]:
df.reset_index(inplace=True)
len_list=df[df['AEP_MW'].isnull()].index.tolist()
df.iloc[len_list]

Empty DataFrame
Columns: [Datetime, AEP_MW]
Index: []

In [24]:
print('values are missing at the following indexes:\n',len_list)

values are missing at the following indexes:
 []

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  8760 non-null   datetime64[ns]
 1   AEP_MW    8760 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 137.0 KB

In [26]:
df.head()

             Datetime  AEP_MW
0 2024-01-01 00:00:00    0.22
1 2024-01-01 01:00:00    0.22
2 2024-01-01 02:00:00    0.22
3 2024-01-01 03:00:00    0.22
4 2024-01-01 04:00:00    0.22

In [27]:
df.isnull().sum()

Datetime    0
AEP_MW      0
dtype: int64

In [28]:
df['AEP_MW'] = df['AEP_MW'].interpolate()

In [29]:
df.isnull().sum()

Datetime    0
AEP_MW      0
dtype: int64

In [30]:
df.to_csv(r'C:\Users\Muhammad Luqman\Desktop\OPEN_ENDED_LAB_21JZELE0444_LUQMAN\2_Missing_Values_Filled.csv',index=False)

In [31]:
print('\tSummary of American Electric Power (AEP)')
print('\nStart Date: \n\t',df.head(1))
print('\nEnd Date: \n\t',  df.tail(1))
print('\nLengthBF: 121273')
print('\nLengthAF: ',len(df))
print('\nSamplesBF: 5053')
print('\nSamplesAF: ',(len(df)/24))
print('\nMissing Points: ',len(len_list))
print('\nMissing Points are at indices:\n ',len_list)

	Summary of American Electric Power (AEP)

Start Date:
	     Datetime  AEP_MW
0 2024-01-01    0.22

End Date:
	                 Datetime  AEP_MW
8759 2024-12-30 23:00:00    0.22

LengthBF: 121273

LengthAF:  8760

SamplesBF: 5053

SamplesAF:  365.0

Missing Points:  0

Missing Points are at indices:
  []

In [32]:
df.iloc[721]

Datetime    2024-01-31 01:00:00
AEP_MW                     0.22
Name: 721, dtype: object

In [33]:
df.isnull().sum()

Datetime    0
AEP_MW      0
dtype: int64

In [34]:
df=pd.read_csv('2_Missing_Values_Filled.csv')
df.describe()

            AEP_MW
count  8760.000000
mean      0.273131
std       0.117803
min       0.210000
25%       0.210000
50%       0.210000
75%       0.220000
max       0.540000

In [35]:
15499+2591*2.8

22753.8